FROM rust:1-alpine3.15 as builder
# This is important, see https://github.com/rust-lang/docker-rust/issues/85
ENV RUSTFLAGS="-C target-feature=-crt-static"

WORKDIR /app
COPY ./ /app

RUN apk add --no-cache musl-dev git
RUN cargo build --release --bin stat_server
RUN strip /app/target/release/stat_server

FROM alpine:latest as production

RUN apk add --no-cache libgcc
COPY --from=builder /app/target/release/stat_server /stat_server

WORKDIR /
EXPOSE 8080 34512

CMD ["/stat_server", "--cloud"]
